version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8000:80
    networks:
      - monitoring
    labels:
      - "prometheus_scrape=true"
  
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: almoxarifado
    ports:
      - "9906:3306"
    volumes:
      - ./php/db:/docker-entrypoint-initdb.d
    networks:
      - monitoring
    labels:
      - "prometheus_scrape=false"  # Banco de dados não expõe métricas HTTP, então desabilitamos a coleta

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - monitoring
    labels:
      - "prometheus_scrape=false"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - monitoring
    depends_on:
      - php-apache-environment
      - db
      - phpmyadmin
    labels:
      - "prometheus_scrape=true"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge