global:
  scrape_interval: 15s  # Tempo de scrape padrão

scrape_configs:
  # Scraping do próprio Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scraping do container PHP (Apache)
  - job_name: 'php-apache'
    static_configs:
      - targets: ['php-apache-environment:80']  # Container PHP Apache expõe na porta 80
    metrics_path: /metrics  # Se seu PHP Apache expuser métricas

  # Scraping de outros containers ou serviços conforme necessário
  # Exemplo para phpMyAdmin, se desejar monitorar métricas HTTP expostas
  - job_name: 'phpmyadmin'
    static_configs:
      - targets: ['phpmyadmin:80']
    metrics_path: /metrics
